version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge