name: ToDo App CD Pipeline

on:
  push:
    branches:
      - trunk

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  docker:
    if: contains(github.event.head_commit.message, 'deploy docker hub') 
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install DevSecOps Engine Tools
        run: pip install devsecops-engine-tools

      - name: Build backend image
        working-directory: todo-app/backend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend:latest .
      
      - name: Push backend image
        working-directory: todo-app/backend
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend:latest
      
      - name: Backend Container Security Scan
        run: devsecops-engine-tools --module engine_container --image_to_scan ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend --platform_devops github --remote_config_repo devsecops_remote_config --use_vulnerability_management false

      - name: Build frontend image
        working-directory: todo-app/frontend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-frontend:latest .
      
      - name: Frontend Container Security Scan
        run: devsecops-engine-tools --module engine_container --image_to_scan ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend --platform_devops github --remote_config_repo devsecops_remote_config --use_vulnerability_management false
      
      - name: Push frontend image
        working-directory: todo-app/frontend
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-frontend:latest