name: ToDo App CI Pipeline

on:
  push:
    branches:
      - trunk
      - feature/*
  pull_request:
    branches:
      - trunk

env:
  VM_PRODUCT_TYPE_NAME: TEAM - The ToDo App
  VM_PRODUCT_NAME: ToDo App
  VM_PRODUCT_DESCRIPTION: ToDo App is a simple web application that allows users to manage their tasks.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: todo-app/backend
        run: npm install

      - name: Run backend tests
        working-directory: todo-app/backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: todo-app/frontend
        run: npm install

      - name: Run frontend tests
        working-directory: todo-app/frontend
        run: npm test
      
      - name: Run frontend build
        working-directory: todo-app/frontend
        run: npm run build

      - name: Install DevSecOps Engine Tools
        run: pip install devsecops-engine-tools

      - name: IaC Security Scan
        run: | 
          output=$(devsecops-engine-tools --module engine_iac --folder_path . --platform_devops github --remote_config_repo devsecops_remote_config --use_vulnerability_management true --send_metrics false --token_vulnerability_management ${{ secrets.TOKEN_DEFECT_DOJO }} --token_cmdb ${{ secrets.TOKEN_DEFECT_DOJO }})
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependencies Security Scan
        run: | 
          output=$(devsecops-engine-tools --module engine_dependencies --folder_path . --platform_devops github --remote_config_repo devsecops_remote_config --token_engine_dependencies ${{ secrets.NVD_API_KEY }} --use_vulnerability_management false)
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}