name: ToDo App Security Scan Pipeline

on:
  pull_request:
    branches:
      - trunk

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Install DevSecOps Engine Tools
        run: pip install devsecops-engine-tools
      
      - name: environment variables
        run: printenv

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List repository files
        run: ls -la
      
      - name: Static Code Scan
        run: |
          output=$(devsecops-engine-tools --module engine_code --folder_path . --platform_devops github --remote_config_repo devsecops_remote_config --use_vulnerability_management false)
          echo "$output"
        #  if [[ $output == *"✘Failed"* ]]; then
        #    exit 1
        #  fi

      - name: Secret Code Scan
        run: |
          output=$(devsecops-engine-tools --module engine_secret --folder_path . --platform_devops github --remote_config_repo devsecops_remote_config --use_vulnerability_management false)
          echo "$output"
        #  if [[ $output == *"✘Failed"* ]]; then
        #    exit 1
        #  fi